services:
  - type: web
    name: sams
    env: java
    plan: free
    buildCommand: mvn -DskipTests clean package
    startCommand: java -jar target/sams-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17

